In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
df = pd.read_csv('/content/data (2).csv')

In [37]:
df.head(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

#### Data Cleaning

In [39]:
#fillna
#dropna

df.dropna(how='any',inplace=True)

In [40]:
len(df)

569

In [42]:
df.diagnosis.value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [43]:
df.diagnosis.value_counts()/len(df)*100

diagnosis
B    62.741652
M    37.258348
Name: count, dtype: float64

#### **Splitting the data into X & y**

In [44]:
X = df.drop(['id','diagnosis'],axis=1)

In [46]:
y = df.diagnosis.values

#### **Train Test Split**

In [47]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [48]:
len(X_train)

426

In [49]:
len(X_test)

143

#### **Feature Scaling**

In [50]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [51]:
X_train_sc

array([[ 3.39249207e+00, -4.68662132e-01,  3.49166595e+00, ...,
         2.39481393e+00,  1.14330451e+00,  1.56606007e-01],
       [-1.23880932e+00,  1.10866842e-01, -1.24114677e+00, ...,
        -1.38656490e+00, -1.50791979e+00,  2.47478625e-01],
       [-1.26902041e+00, -2.93417810e-02, -1.28590349e+00, ...,
        -1.16655140e+00, -5.74857938e-01, -3.13515342e-01],
       ...,
       [-7.01631744e-02,  1.00119159e+00,  2.33021225e-03, ...,
         1.27897753e+00,  2.26358265e+00,  1.23079389e+00],
       [-5.08804905e-01, -8.33204550e-01, -5.35172740e-01, ...,
        -1.02102711e+00, -6.80544556e-01, -1.16130959e+00],
       [-5.27337017e-02,  2.88464430e-01, -7.32495431e-02, ...,
        -7.16161985e-01, -1.03233001e+00, -1.30578988e-02]])

In [52]:
X_test_sc

array([[-0.57561788, -1.4080599 , -0.57739607, ..., -0.63386342,
        -0.22911172, -0.24417901],
       [-0.39260842, -1.70483482, -0.44861492, ..., -0.50906395,
        -0.23817057,  0.49750964],
       [-0.78767647, -0.19992894, -0.79146834, ..., -0.46130675,
         0.19212495, -0.9107533 ],
       ...,
       [-0.73538805, -0.16721359, -0.76697881, ..., -0.79560713,
         0.56353792, -0.77785866],
       [-1.25507683, -0.96406593, -1.17063381, ...,  0.61518252,
         0.26459577,  2.13952007],
       [ 1.59725638,  0.87500383,  1.57894924, ...,  0.99663938,
        -0.53862253, -0.48055287]])

#### **Model Building** - **kNN**

In [53]:
from sklearn.neighbors import KNeighborsClassifier

# Initiate the classifier
model_knn = KNeighborsClassifier()

# Passing the data to classifier
model_knn.fit(X_train_sc, y_train)

KNeighborsClassifier()

In [54]:
y_pred_knn = model_knn.predict(X_test_sc)

In [55]:
y_pred_knn

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'M',
       'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M',
       'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M',
       'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'M', 'M', 'M', 'M',
       'M', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'M', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B',
       'B', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M'],
      dtype=object)

In [56]:
y_test

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'M',
       'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M',
       'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M',
       'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B',
       'M', 'M', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B',
       'B', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M'],
      dtype=object)

In [60]:
# Classification metrics to check how the model behaves

from sklearn.metrics import accuracy_score

print(round(accuracy_score(y_test, y_pred_knn)*100,2))

95.8


#### **Model Building** - **DT**

In [69]:
from sklearn.tree import DecisionTreeClassifier

# Initiate the classifier
model_dt = DecisionTreeClassifier()

# Passing the data to classifier
model_dt.fit(X_train_sc, y_train)

DecisionTreeClassifier()

In [70]:
y_pred_dt = model_dt.predict(X_test_sc)

In [71]:
# Classification metrics to check how the model behaves

from sklearn.metrics import accuracy_score

print(round(accuracy_score(y_test, y_pred_dt)*100,2))

92.31


#### **Model Building** - **RF**

In [72]:
from sklearn.ensemble import RandomForestClassifier

# Initiate the classifier
model_rf = RandomForestClassifier()

# Passing the data to classifier
model_rf.fit(X_train_sc, y_train)

RandomForestClassifier()

In [73]:
y_pred_rf = model_rf.predict(X_test_sc)

In [74]:
# Classification metrics to check how the model behaves

from sklearn.metrics import accuracy_score

print(round(accuracy_score(y_test, y_pred_rf)*100,2))

94.41


#### **Model Building** - **NB**

In [75]:
from sklearn.naive_bayes import GaussianNB

# Initiate the classifier
model_nb = GaussianNB()

# Passing the data to classifier
model_nb.fit(X_train_sc, y_train)

GaussianNB()

In [76]:
y_pred_nb = model_nb.predict(X_test_sc)

In [77]:
# Classification metrics to check how the model behaves

from sklearn.metrics import accuracy_score

print(round(accuracy_score(y_test, y_pred_nb)*100,2))

94.41


#### **Predict for a new patient**

In [61]:
new_data = [[22.57,16.77,121.9,1326,0.08474,0.07864,0.0969,0.07017,0.1812,
             0.05667,0.5435,0.7339,3.398,74.08,0.105225,0.01308,0.0186,0.0234,
             0.01389,0.003532,23.99,23.41,158.8,1956,0.2238,0.1866,0.2416,0.186,0.275,0.09902]]

In [62]:
new_data_sc = sc.transform(new_data)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [63]:
new_data_sc

array([[ 2.47453984e+00, -6.29902048e-01,  1.28338595e+00,
         2.02040603e+00, -8.09973385e-01, -5.09511955e-01,
         1.00810096e-01,  5.58688461e-01,  3.02083270e-04,
        -8.76350721e-01,  6.22151152e-01, -8.59438792e-01,
         3.32529675e-01,  1.02057894e+00,  3.36026060e+01,
        -7.20281037e-01, -4.97566969e-01,  2.01629688e+00,
        -7.84576117e-01, -1.14870174e-01,  1.62551181e+00,
        -4.21223194e-01,  1.55006015e+00,  1.93949078e+00,
         3.78111401e+00, -4.71453836e-01, -1.85414758e-01,
         1.04920234e+00, -2.75915791e-01,  7.27580203e-01]])

In [64]:
y_pred_single = model_knn.predict(new_data_sc)

In [65]:
y_pred_single

array(['B'], dtype=object)

In [66]:
new_data_1 = [[20.57,17.77,132.9,1326,0.08474,0.07864,0.0869,0.07017,0.1812,
               0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.0186,
               0.0134,0.01389,0.003532,24.99,23.41,
               158.8,1956,0.1238,0.1866,0.2416,0.186,0.275,0.08902]]

In [67]:
new_data_1_sc = sc.transform(new_data_1)
y_pred_single2 = model_knn.predict(new_data_1_sc)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [68]:
y_pred_single2

array(['M'], dtype=object)